const Actions = {
    MYLIST_ADD_BOOK: 'MYLIST_ADD_BOOK', 
    MYLIST_VIEW_BOOK: 'MYLIST_VIEW_BOOK',
    MYLIST_DELETE_BOOK: 'MYLIST_DELETE_BOOK',
    MYLIST_MARK_AS_READED: 'MYLIST_MARK_AS_READED',
    SEARCH_SET_KEYWORDS: 'SEARCH_SET_KEYWORDS',
    SEARCH_SEARCH_BOOKS: 'SEARCH_SEARCH_BOOKS',
    SEARCH_CLEAR_BOOKS: 'SEARCH_CLEAR_BOOKS',
    SEARCH_ADD_BOOK: 'SEARCH_ADD_BOOK' 
}; 

export default Actions;